import { Router, type Request } from 'express'
import type { Person, Prisma } from '@prisma/client'
import { prisma } from '../db.js'
import { limitOf, optionalDate, route, str } from '../api.js'
import { badRequest, forbidden, notFound } from '../errors.js'
import { requireAuth, requirePerson, requireScope, type Auth } from '../auth/middleware.js'
import { SELF } from '../auth/apiKeys.js'
import { parseGeo } from '../lib/geo.js'
import { addPunch, board, crewPunch, editPunch, personState, punchIn, punchInclude, punchNext, punchOut, type Actor, type CrewAction, type PunchInput } from '../services/punch.js'

export const punchesRouter = Router()

/** The person a punch call is for. An integration that forgot X-Act-As is told so. */
function punchCaller(req: Request): { auth: Auth; person: Person } {
  const auth = requireAuth(req)
  if (auth.via === 'key' && !auth.person && auth.scopes.has('punch:write:any')) requirePerson(auth)
  requireScope(req, SELF)
  return { auth, person: requirePerson(auth) }
}

const actorOf = (auth: Auth): Actor => ({
  companyId: auth.companyId,
  apiKeyId: auth.apiKeyId,
  source: auth.via === 'key' ? 'api' : 'app',
})

function inputOf(req: Request): PunchInput {
  const b = (req.body ?? {}) as Record<string, unknown>
  const ref = b.jobRef as Record<string, unknown> | undefined
  return {
    jobId: str(b.jobId, 80) || undefined,
    jobRef: ref && typeof ref === 'object' ? { system: str(ref.system, 40).toLowerCase(), externalId: str(ref.externalId, 200) } : undefined,
    phaseId: str(b.phaseId, 80) || undefined,
    phaseKey: str(b.phaseKey, 80) || undefined,
    geo: parseGeo(b.geo),
    at: optionalDate(b.at, 'at'),
    clientId: str(b.clientId, 80) || undefined,
    notes: str(b.notes, 500),
  }
}

const PUNCH_BODY = {
  geo: '{ lat, lng, accuracyM } from the device at the moment of the punch',
  at: 'ISO date-time the punch really happened, for punches sent late. Defaults to now',
  clientId: 'Id generated by the sender. Re-sending the same clientId does nothing',
}

route(
  punchesRouter,
  { method: 'get', path: '/me/state', tag: 'Punching', summary: 'On or off the clock, the open segment, today so far, and the next phase.', access: [SELF] },
  async (req) => personState(punchCaller(req).person),
)

route(
  punchesRouter,
  {
    method: 'post',
    path: '/punches/in',
    tag: 'Punching',
    summary: 'Clock in. If already on the clock, switch to this job and phase.',
    access: [SELF],
    body: {
      jobId: 'Job to charge',
      jobRef: 'Alternative to jobId: { system, externalId } of the job in another system',
      phaseId: 'Phase of the day',
      phaseKey: 'Alternative to phaseId, e.g. "shop-load". Defaults to the first phase',
      notes: 'Optional note',
      ...PUNCH_BODY,
    },
  },
  async (req) => {
    const { auth, person } = punchCaller(req)
    const result = await punchIn(actorOf(auth), person, inputOf(req))
    return { ...result, state: await personState(person) }
  },
)

route(
  punchesRouter,
  {
    method: 'post',
    path: '/punches/next',
    tag: 'Punching',
    summary: 'Move to the next phase of the day on the same job.',
    access: [SELF],
    body: { phaseId: 'Jump to this phase instead of the next one', phaseKey: 'Alternative to phaseId', ...PUNCH_BODY },
  },
  async (req) => {
    const { auth, person } = punchCaller(req)
    const result = await punchNext(actorOf(auth), person, inputOf(req))
    return { ...result, state: await personState(person) }
  },
)

route(
  punchesRouter,
  { method: 'post', path: '/punches/out', tag: 'Punching', summary: 'Clock out.', access: [SELF], body: { geo: PUNCH_BODY.geo, at: PUNCH_BODY.at } },
  async (req) => {
    const { auth, person } = punchCaller(req)
    const result = await punchOut(actorOf(auth), person, inputOf(req))
    return { ...result, state: await personState(person) }
  },
)

route(
  punchesRouter,
  {
    method: 'get',
    path: '/punches',
    tag: 'Punching',
    summary: 'Segments, newest first. Without punch:read you see only your own.',
    access: ['punch:read', SELF],
    query: {
      personId: 'Only this person',
      jobId: 'Only this job',
      from: 'ISO date-time; segments starting at or after it',
      to: 'ISO date-time; segments starting before it',
      updatedSince: 'ISO date-time; only segments changed after it',
      open: 'true for segments still on the clock',
      limit: 'Page size, 100 by default, 500 at most',
      cursor: 'nextCursor from the previous page',
    },
  },
  async (req) => {
    const auth = requireScope(req, 'punch:read', SELF)
    const all = auth.scopes.has('punch:read')
    const personId = all ? str(req.query.personId, 80) || undefined : requirePerson(auth).id
    const from = optionalDate(req.query.from, 'from')
    const to = optionalDate(req.query.to, 'to')
    const where: Prisma.PunchWhereInput = {
      companyId: auth.companyId,
      personId,
      jobId: str(req.query.jobId, 80) || undefined,
      clockIn: from || to ? { gte: from, lt: to } : undefined,
      updatedAt: req.query.updatedSince ? { gt: optionalDate(req.query.updatedSince, 'updatedSince') } : undefined,
      clockOut: req.query.open === 'true' ? null : undefined,
    }
    const limit = limitOf(req.query.limit)
    const cursor = str(req.query.cursor, 80)
    const rows = await prisma.punch.findMany({
      where,
      include: { ...punchInclude, person: { select: { id: true, name: true, email: true } } },
      orderBy: [{ clockIn: 'desc' }, { id: 'desc' }],
      take: limit + 1,
      ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
    })
    const page = rows.slice(0, limit)
    return { data: page, nextCursor: rows.length > limit ? page[page.length - 1].id : null }
  },
)

route(
  punchesRouter,
  { method: 'get', path: '/punches/:id', tag: 'Punching', summary: 'One segment with its edit history.', access: ['punch:read', SELF] },
  async (req) => {
    const auth = requireScope(req, 'punch:read', SELF)
    const punch = await prisma.punch.findFirst({
      where: { id: req.params.id, companyId: auth.companyId },
      include: { ...punchInclude, person: { select: { id: true, name: true, email: true } }, edits: { orderBy: { at: 'asc' } } },
    })
    if (!punch) throw notFound('Punch')
    if (!auth.scopes.has('punch:read') && punch.personId !== auth.person?.id) throw forbidden('That is not your punch.')
    return { punch }
  },
)

route(
  punchesRouter,
  {
    method: 'patch',
    path: '/punches/:id',
    tag: 'Punching',
    summary: 'Correct a segment. The change and the reason are kept in its history.',
    access: ['punch:write:any'],
    body: {
      reason: 'Why the change is being made (required)',
      clockIn: 'New start',
      clockOut: 'New end, or null to reopen',
      jobId: 'Move to another job',
      phaseId: 'Move to another phase, or null',
      notes: 'Replace the note',
    },
  },
  async (req) => {
    const auth = requireScope(req, 'punch:write:any')
    const b = (req.body ?? {}) as Record<string, unknown>
    if (b.clockOut !== undefined && b.clockOut !== null && !String(b.clockOut)) throw badRequest('clockOut must be a date-time or null.')
    const punch = await editPunch(
      { companyId: auth.companyId, personId: auth.via === 'session' ? auth.person?.id ?? null : null, apiKeyId: auth.apiKeyId },
      req.params.id,
      {
        clockIn: optionalDate(b.clockIn, 'clockIn'),
        clockOut: b.clockOut === null ? null : optionalDate(b.clockOut, 'clockOut'),
        jobId: str(b.jobId, 80) || undefined,
        phaseId: b.phaseId === null ? null : str(b.phaseId, 80) || undefined,
        notes: b.notes === undefined ? undefined : str(b.notes, 500),
      },
      str(b.reason, 500),
    )
    return { punch }
  },
)

route(
  punchesRouter,
  { method: 'get', path: '/board', tag: 'Views', summary: "Tower board: everyone's current job and phase today.", access: ['punch:read'] },
  async (req) => board(requireScope(req, 'punch:read').companyId),
)


route(
  punchesRouter,
  {
    method: 'post',
    path: '/punches',
    tag: 'Punching',
    summary: 'Add a segment that was never punched. The reason is kept in its history.',
    access: ['punch:write:any'],
    status: 201,
    body: {
      personId: 'Whose time this is',
      jobId: 'Job to charge',
      phaseId: 'Phase of the day (optional)',
      clockIn: 'ISO date-time',
      clockOut: 'ISO date-time',
      notes: 'Optional note',
      reason: 'Why it is being added (required)',
    },
  },
  async (req) => {
    const auth = requireScope(req, 'punch:write:any')
    const b = (req.body ?? {}) as Record<string, unknown>
    const clockIn = optionalDate(b.clockIn, 'clockIn')
    const clockOut = optionalDate(b.clockOut, 'clockOut')
    if (!clockIn) throw badRequest('clockIn is required.', { field: 'clockIn' })
    if (!clockOut) throw badRequest('clockOut is required.', { field: 'clockOut' })
    const punch = await addPunch(
      { companyId: auth.companyId, personId: auth.via === 'session' ? auth.person?.id ?? null : null, apiKeyId: auth.apiKeyId },
      {
        personId: str(b.personId, 80),
        jobId: str(b.jobId, 80),
        phaseId: str(b.phaseId, 80) || null,
        clockIn,
        clockOut,
        notes: str(b.notes, 500),
      },
      str(b.reason, 500),
    )
    return { punch }
  },
)

const CREW_ACTIONS: CrewAction[] = ['in', 'next', 'out']

route(
  punchesRouter,
  {
    method: 'post',
    path: '/punches/crew',
    tag: 'Punching',
    summary: 'A lead punches several people at once: clock in (or switch), next phase, or clock out. Each person succeeds or fails separately.',
    access: ['punch:crew'],
    body: {
      action: 'in | next | out',
      personIds: 'Array of person ids',
      jobId: 'For in: the job',
      jobRef: 'For in: alternative to jobId',
      phaseId: 'For in or next: the phase',
      phaseKey: 'Alternative to phaseId',
      geo: "The lead's position, stamped on every punch",
    },
  },
  async (req) => {
    const auth = requireScope(req, 'punch:crew')
    const b = (req.body ?? {}) as Record<string, unknown>
    const action = str(b.action, 10) as CrewAction
    if (!CREW_ACTIONS.includes(action)) throw badRequest('action must be in, next or out.', { field: 'action' })
    const ids = Array.isArray(b.personIds) ? b.personIds.map((v) => str(v, 80)).filter(Boolean) : []
    if (!ids.length) throw badRequest('Name at least one person.', { field: 'personIds' })
    if (ids.length > 50) throw badRequest('50 people at most per crew punch.', { field: 'personIds' })
    const input = inputOf(req)
    if (action === 'in' && !input.jobId && !input.jobRef) throw badRequest('Pick the job for the crew.', { field: 'jobId' })
    const results = await crewPunch(
      { ...actorOf(auth), source: 'lead', enteredById: auth.person?.id ?? null },
      ids,
      action,
      { ...input, clientId: undefined },
    )
    return { results, ok: results.filter((r) => r.ok).length, failed: results.filter((r) => !r.ok).length }
  },
)
